name: Docker Image CI

on:
  push:
    branches: [ "uas-global" ]
  pull_request:
    branches: [ "uas-global" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag elbiii/mickymouse:latest
    - name: Push Docker Image
      run: docker login -u elbiii -p ${{ secrets.DOCKERHUB_SECRET }} && docker push elbiii/mickymouse:latest
